# Generated by Django 3.1.7 on 2021-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(max_length=50)),
                ('current_ogranisation', models.CharField(max_length=50, null=True)),
                ('previous_organisation', models.CharField(max_length=50, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
